-- Agent Tasks Schema Database Schema
-- Generated by Database Builder Builder Agent
-- Requirements: task tracking, agent assignment, status updates

CREATE TABLE IF NOT EXISTS agent_tasks_schema (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(50) DEFAULT 'active',
    data JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Add indexes for performance
    INDEX idx_agent_tasks_schema_status (status),
    INDEX idx_agent_tasks_schema_created (created_at)
);

-- Add triggers for updated_at
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_agent_tasks_schema_timestamp
    BEFORE UPDATE ON agent_tasks_schema
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

-- Sample data
INSERT INTO agent_tasks_schema (name, description, data) VALUES
('Sample Agent Tasks Schema', 'Generated sample data', '{"type": "sample", "version": "1.0"}');
