-- System Metrics Schema Database Schema
-- Generated by Database Builder Builder Agent
-- Requirements: performance data, resource usage, historical tracking

CREATE TABLE IF NOT EXISTS system_metrics_schema (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(50) DEFAULT 'active',
    data JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Add indexes for performance
    INDEX idx_system_metrics_schema_status (status),
    INDEX idx_system_metrics_schema_created (created_at)
);

-- Add triggers for updated_at
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_system_metrics_schema_timestamp
    BEFORE UPDATE ON system_metrics_schema
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

-- Sample data
INSERT INTO system_metrics_schema (name, description, data) VALUES
('Sample System Metrics Schema', 'Generated sample data', '{"type": "sample", "version": "1.0"}');
